apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "roar-db.name" . }}
  labels:
    app: {{ template "roar-db.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "roar-db.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        {{- if eq  .Values.stage "PROD" }}
        image: "{{- .Values.image.prod.repository }}:{{ .Values.image.prod.tag -}}"
        {{ else if eq  .Values.stage  "TEST" }}
        image: "{{- .Values.image.test.repository }}:{{ .Values.image.test.tag -}}"
        {{ else }}
        image: "{{- fail "A valid .Values.stage entry required!" }}"
        {{ end -}}
        imagePullPolicy: Always
        ports:
        - name: {{ .Values.deployment.ports.name }}
          containerPort: {{ .Values.deployment.ports.containerPort }}
        env:
          {{- include "roar-db.environment-values" . | indent 10 }}
       

